apiVersion: apps/v1
kind: Deployment
metadata:
  name: docconverter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docconverter
  template:
    metadata:
      labels:
        app: docconverter
    spec:
      containers:
      - name: docconverter
        image: eliejaz/docconverter:latest
        ports:
        - containerPort: 8080
